##############################################################################
#
# LAB NOTEBOOK
#
# bmh March 2012
#
# Overview
#   A place to keep track of what experiments I have done on the generalize
#   project over time.
#
# Format
#   Entries are to be chronological and dated.  When edits occur they should be
#   dated.  Objects generated by scripts should often be hashed to assure that
#   they remain stable on subsequent runs using the following function:

	library(digest)
	hash <- function(object) {
		digest(object, "md5")
	}

#   Because this work is chronological, dependencies and constants will
#   be loaded as they are used.  It may be necessary to cleanup existing data
#   and complex routines should be nested so that they only run when the run_all
#   configuration is set.

    run_all = FALSE       # set to true to run every script all time
    
#
#   Often I will want to reference outside resources.  This is completely fine.
#
##############################################################################

# 21 March 2012
#
#    Last week I ran a preliminary analysis in the generalize vein.  It is
#    available in the script 'generalize.R'.  The main result is that gbm
#    modeling did the best, but that inter-species effects were not helpful
#    and my ignorance of censoring made the data difficult to interepret.
#    For example it looked as if control dogs lived less than treatment dogs
#    but this is probably owing to the fact that they were assigned as control
#    dogs at birth whereas treatment dogs were not assigned to their treatment
#    until they reached a certain minimum age.  Similarly, animals that were 
#    given a huge number of fractions were sometimes predicted to live longer.
#    However, this is a result of the fact that they had to live such a long 
#    time to recieve so many fractions.  In the future, I will try to predict
#    how long 