##############################################################################
#
# LAB NOTEBOOK
#
# bmh March 2012
#
# Overview
#   A place to keep track of what experiments I have done on the generalize
#   project over time.
#
# Format
#   Entries are to be chronological and dated.  When edits occur they should be
#   dated.  Objects generated by scripts should often be hashed to assure that
#   they remain stable on subsequent runs using the following function:

	library(digest)
	hash <- function(object) {
		digest(object, "md5")
	}

#   Because this work is chronological, dependencies and constants will
#   be loaded as they are used.  It may be necessary to cleanup existing data
#   and complex routines should be nested so that they only run when the run_all
#   configuration is set.

    run_all = FALSE       # set to true to run every script all time
    
#
#   Often I will want to reference outside resources.  This is completely fine.
#
##############################################################################

